"""steam_id

Revision ID: 1d38dc046cb1
Revises: 3aa0b95e7b50
Create Date: 2023-11-16 12:48:15.767714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d38dc046cb1'
down_revision: Union[str, None] = '3aa0b95e7b50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revoked_tokens')
    op.add_column('User', sa.Column('steam_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'User', ['steam_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='unique')
    op.drop_column('User', 'steam_id')
    op.create_table('revoked_tokens',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='revoked_tokens_pkey')
    )
    # ### end Alembic commands ###
