"""match

Revision ID: ee1c3c915edc
Revises: e57dd4ffe486
Create Date: 2023-11-16 19:46:45.016614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee1c3c915edc'
down_revision: Union[str, None] = 'e57dd4ffe486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Match', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Match', 'status')
    # ### end Alembic commands ###
